### ISSUE TITLE
Authentication errors

### ISSUE THREAD

**Issue by your-extended-car-warranty** [tgiversen/CSC289-Group3#34]
When trying to log in/register a new account, the form will not submit, and an error is logged in the web browser's console.

The Flask server has been started from the command ```flask run --debug``` and the Vite + React server has been started using ```npm run dev``` in VS Code.

**Comment by your-extended-car-warranty** [comment]
I've merged tk_branch to main, which should fix the issue.

The fixes are referenced in [this test report](https://github.com/tgiversen/CSC289-Group3/blob/main/sprintdocs/sprint4_week1_test_report.md) under debugging.

**Comment by CSC120shahe** [comment]
Hi @jijisusu3  @your-extended-car-warranty 
when I click the "create account" button, it still shows the error below. pls help take a look.

<img width="1774" height="861" alt="Image" src="https://github.com/user-attachments/assets/c57a58b0-274c-4945-addb-e5c9a3907cb5" />
